export const TOOLS = {
  aurelia: { name: 'aurelia', label: 'Aurelia', link: 'https://aurelia.io/' },
  angular: { name: 'angular', label: 'Angular', link: 'https://angular.io/' },
  aws: { name: 'aws', label: 'AWS', link: 'https://aws.amazon.com/' },
  css3: { name: 'css3', label: 'CSS3', link: 'https://en.wikipedia.org/wiki/CSS' },
  docker: { name: 'docker', label: 'Docker', link: 'https://www.docker.com/' },
  electron: { name: 'electron', label: 'Electron', link: 'https://www.electronjs.org/' },
  expressjs: { name: 'expressjs', label: 'ExpressJS', link: 'https://expressjs.com/' },
  git: { name: 'git', label: 'Git', link: 'https://git-scm.com/' },
  gulp: { name: 'gulp', label: 'Gulp', link: 'https://gulpjs.com/' },
  html5: { name: 'html5', label: 'HTML5', link: 'https://en.wikipedia.org/wiki/HTML5' },
  javascript: { name: 'javascript', label: 'JavaScript', link: 'https://www.javascript.com/' },
  jenkins: { name: 'jenkins', label: 'Jenkins', link: 'https://www.jenkins.io/' },
  jwt: { name: 'jwt', label: 'JSON Web Tokens', link: 'https://jwt.io/' },
  kubernetes: { name: 'kubernetes', label: 'Kubernetes', link: 'https://kubernetes.io/' },
  mongodb: { name: 'mongodb', label: 'Mongo DB', link: 'https://www.mongodb.com/' },
  nodejs: { name: 'nodejs', label: 'NodeJS', link: 'https://nodejs.org/' },
  rabbitmq: { name: 'rabbitmq', label: 'RabbitMQ', link: 'https://www.rabbitmq.com/' },
  react: { name: 'react', label: 'React', link: 'https://reactjs.org/' },
  redux: { name: 'redux', label: 'Redux', link: 'https://redux.js.org/' },
  rxjs: { name: 'rxjs', label: 'RxJS', link: 'https://angular.io/guide/rx-library' },
  typescript: { name: 'typescript', label: 'TypeScript', link: 'https://www.typescriptlang.org/' },
  vuejs: { name: 'vuejs', label: 'VueJS', link: 'https://vuejs.org/' },
  webpack: { name: 'webpack', label: 'Webpack', link: 'https://webpack.js.org/' },
  webrtc: { name: 'webrtc', label: 'Webrtc', link: 'https://webrtc.org/' },
  wordpress: { name: 'wordpress', label: 'Wordpress', link: 'https://wordpress.com/' }
}
